feat: invitaion form desktop view
prodbyola/basable pull request #29
Opened 2024-07-20 04:37 UTC by ShedrachJonah11

2024-07-20 12:25 UTC, prodbyola requested changes
Hey @ShedrachJonah11 
Thanks for your contribution! This is a job well done. The components are perfectly developed. Now we just need to reduce the size of the background image. 24MB+ is huge. You can make use of any image compression tool without losing too much quality.

Looking forward to merging the PR. Thank you.

2024-07-20 12:37 UTC, ShedrachJonah11 commented
Alright, 
Will do so

2024-07-20 16:47 UTC, ShedrachJonah11 commented
> Alright, Will do so

Completed

2024-07-21 11:02 UTC, prodbyola approved these changes

2024-07-21 11:03 UTC, merged